spring:
  # mysql
  datasource:
    url: jdbc:mysql://localhost:3306/digitalcoininvestdb?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: rydb1234
    driver-class-name: com.mysql.cj.jdbc.Driver
thymeleaf.cache : false

spring.devtools.restart.enabled: true

spring.devtools.restart.additional-paths: src/main/java

mybatis.mapper-locations: classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case: true
server:
  port: 8084